Repository oshi/oshi, pull requests merged in 2020-10, with the labels that each got.

#1350 Feature/get local interfaces
  .editorconfig
  CHANGELOG.md
  oshi-core/src/main/java/oshi/hardware/HardwareAbstractionLayer.java
  oshi-core/src/main/java/oshi/hardware/common/AbstractHardwareAbstractionLayer.java
  oshi-core/src/main/java/oshi/hardware/common/AbstractNetworkIF.java
  oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxHardwareAbstractionLayer.java
  oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxNetworkIF.java
  oshi-core/src/main/java/oshi/hardware/platform/mac/MacHardwareAbstractionLayer.java
  oshi-core/src/main/java/oshi/hardware/platform/mac/MacNetworkIF.java
  oshi-core/src/main/java/oshi/hardware/platform/unix/aix/AixHardwareAbstractionLayer.java
  oshi-core/src/main/java/oshi/hardware/platform/unix/aix/AixNetworkIF.java
  oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdHardwareAbstractionLayer.java
  oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdNetworkIF.java
  oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisHardwareAbstractionLayer.java
  oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisNetworkIF.java
  oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsHardwareAbstractionLayer.java
  oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsNetworkIF.java
  oshi-core/src/test/java/oshi/hardware/NetworksTest.java
Labels: hacktoberfest-accepted

#1353 Passes default locale setting when executing commands.
  CHANGELOG.md
  oshi-core/src/main/java/oshi/util/ExecutingCommand.java
Labels: hacktoberfest-accepted, i18n

#1362 Logical cores iteration
  CHANGELOG.md
  oshi-core/src/main/java/oshi/driver/windows/LogicalProcessorInformation.java
  oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdCentralProcessor.java
Labels: hacktoberfest-accepted

#1359 make suppressed types/paths per globalconfig and set on startup if not set before
  CHANGELOG.md
  oshi-core/src/main/java/oshi/software/common/AbstractFileSystem.java
  oshi-core/src/main/resources/oshi.properties
Labels: hacktoberfest-accepted

#1368 Backup for process name and state
  CHANGELOG.md
  oshi-core/src/main/java/oshi/software/os/linux/LinuxOSProcess.java
Labels: hacktoberfest-accepted

#1369 Add messages to unit test assertions
  oshi-core/src/test/java/oshi/SourceCodeTest.java
Labels: hacktoberfest-accepted

#1371 added unit test message
  oshi-core/src/test/java/oshi/util/UtilTest.java
Labels: hacktoberfest-accepted

#1376 Addition of assertion messages for GlobalConfigTest
  oshi-core/src/test/java/oshi/util/GlobalConfigTest.java
Labels: hacktoberfest-accepted

#1377 Add Assert messages to ParseUtilTest
  oshi-core/src/test/java/oshi/util/ParseUtilTest.java
Labels: hacktoberfest-accepted

#1379 Add `squashfs` as a pseudo file system so it will be skipped by default
  CHANGELOG.md
  oshi-core/src/main/resources/oshi.properties
Labels: hacktoberfest-accepted

#1381 Adds assert messages to a method in ParseUtilTest
  oshi-core/src/test/java/oshi/util/ParseUtilTest.java
Labels: hacktoberfest-accepted

#1380 Fix exception sorting child process list on Windows
  CHANGELOG.md
  oshi-core/src/main/java/oshi/software/os/windows/WindowsOperatingSystem.java
  oshi-core/src/test/java/oshi/software/os/OperatingSystemTest.java
Labels: confirmed bug, hacktoberfest-accepted

#1385 Add Assert messages to ParseUtilTest
  oshi-core/src/test/java/oshi/util/ParseUtilTest.java
Labels: hacktoberfest-accepted
